services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  alembic:
    build: .
    command: poetry run alembic upgrade head
    depends_on:
      - db
