services:
  postgres:
    image: postgres
    container_name: postgres
    command: postgres -c 'max_connections=2000' -c 'jit=off'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./deployment/.pgdata:/var/lib/postgresql/data

volumes:
  docker:
    driver: local
  postgres:
